default_context:
  name: "bpyutils"
  version: "0.2.0"
  slug: "bpyutils"
  command: "bpyutils"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "A collection of various common Python utilities."
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "utilities python boilpy"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "bpyutils"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "bpyutils"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/bpyutils"